import logo from './logo.svg'
import menu from './menu.svg'
import wallet from './wallet.svg'
import user from './user.svg'
import banner from './banner.svg'
import bell from './bell.svg'
import fire from './fire.svg'
import search from './search.svg'
import slot from './slot.svg'
import woman from './woman.svg'
import jackpot from './jackpot.svg'
import newIcon from './newIcon.svg'
import ball from './ball.svg'
import star from './star.svg'
import invite from './invite.svg'
import dice from './dice.svg'
import cashier from './cashier.svg'
import bigBadWolf from './game/big-bad-wolf.svg'
import anacondaWild2 from './game/anaconda-wild-2.svg'
import azteca from './game/azteca.svg'
import beachLive from './game/azteca.svg'
import bookOfEgypt from './game/book-of-egypt.svg'
import candy from './game/candy.svg'
import crocodileBlits from './game/crocodile-blits.svg'
import incaJackpot from './game/inca-jackpot.svg'
import mayaJackpot from './game/maya-jackpot.svg'
import piratesPower from './game/pirates-power.svg'
import prideOfPersia from './game/pride-of-persia.svg'
import filter from './filter.svg'
import everyMatrix from './logo/every-matrix.svg'
import evolution from './logo/evolution.svg'
import gameArt from './logo/game-art.svg'
import haberno from './logo/habanero.svg'
import hacksawGaming from './logo/hacksaw-gaming.svg'
import inbetGames from './logo/inbet-games.svg'
import netent from './logo/netent.svg'
import pg from './logo/pg.svg'
import playGo from './logo/play-go.svg'
import play from './logo/play.svg'
import playson from './logo/playson.svg'
import playtech from './logo/playtech.svg'
import pragmaticPlay2 from './logo/pragmatic-play-2.svg'
import pragmaticPlay from './logo/pragmatic-play.svg'
import redTiger from './logo/red-tiger.svg'
import relaxGaming from './logo/relax-gaming.svg'


export {
    logo, menu, wallet, user, banner, bell, search, fire, slot, woman, jackpot, newIcon, ball, star, invite, dice, cashier, filter, bigBadWolf, anacondaWild2, azteca, beachLive, bookOfEgypt, candy, crocodileBlits, incaJackpot, mayaJackpot, piratesPower, prideOfPersia, everyMatrix, evolution, gameArt, haberno, hacksawGaming, inbetGames, netent, pg, playGo, play, playson, playtech, pragmaticPlay, pragmaticPlay2, redTiger, relaxGaming
}